# Li-Chi Boba Shop
Lebintiti Kobe

- [Overview](#overview)
  - [Objective](#objective)
- [Data Structure](#data-structure)
- [Key Recommendations](#key-recommendations)
- [Analysis Approach](#analysis-approach)
  - [Breaking Down The Metric](#breaking-down-the-metric)
- [Recommendations Deep Dive](#recommendations-deep-dive)
  - [Opportunity 1 : Increasing number of
    customers](#opportunity-1--increasing-number-of-customers)
  - [Opportunity 2 : Increasing number of times customers order per
    week](#opportunity-2--increasing-number-of-times-customers-order-per-week)
  - [Opportunity 3 : Increasing number of drinks per
    order](#opportunity-3--increasing-number-of-drinks-per-order)

# Overview

You are the business analyst on the Strategy and Operations team for the
Li-Chi Boba Shop Company. The company has physical boba shops in three
cities in California, and customers place their orders via the app and
pick up the orders in person.

## Objective

The objective of Li-Chi Boba Shop this year is to grow total sales
revenue (please note that menu prices for the year have been set
already). Based on the one week app data attached, please present your
findings and provide a set of recommendations for growing total sales
revenue. Feel free to make your own assumptions.

# Data Structure

***This dataset contains 1,049 customer orders across multiple cities,
capturing sales, refunds, and customer ratings.***

<img src="images/crt.png" width="400" height="500" />

# Key Recommendations

**Increase Customers** : ***Increase marketing/advertising effort in
best performing city and store, while optimize on worst performing store
to drive acquisition and retention.***

- Increase marketing/advertising effort in City A to acquire new users
  given it’s high orders and revenue.

- Drive traffic to store wehqk (best operational excellence) while
  conducting deep-dives in store acjde (worst operational excellence) to
  increase acquisition and retention.

**Increase Order Frequency** : ***Leverage comms capabilities (email,
push notifications) to increase order frequency.***

- Send email/push notifications around two order peak time (2AM-6AM and
  8PM-9PM) to increase order frequency.

**Increase Order Size :** ***Test benefits/promotions to increase
average order size***.

- Incentivize customers (whose order size falls below 5 drinks/order)
  via benefits/promotions to increase the number of boba sold per order.

# Analysis Approach

## Breaking Down The Metric

**Sales Revenue can be broken down into *\# Units Sold x Avg Selling
Price* , so do increase sales revenue we either have to *increase number
of units sold or average selling price* , but prices are already set** .

Therefore to increase Sales Revenue we focus on increasing number of
units sold . Business opportunities that come to mind are ***Increasing
number of customers , Increasing order frequency and Increasing order
size .***

![](images/approach.png)

# Recommendations Deep Dive

## Opportunity 1 : Increasing number of customers

### Increase marketing spend in City A (highest demand) , to acquire new customers

<div id="vaayhctool" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>@import url("https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Cairo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
#vaayhctool table {
  font-family: Cairo, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
&#10;#vaayhctool thead, #vaayhctool tbody, #vaayhctool tfoot, #vaayhctool tr, #vaayhctool td, #vaayhctool th {
  border-style: none;
}
&#10;#vaayhctool p {
  margin: 0;
  padding: 0;
}
&#10;#vaayhctool .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: 400;
  font-style: normal;
  background-color: #FFFFFF;
  width: 450px;
  border-top-style: none;
  border-top-width: 3px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}
&#10;#vaayhctool .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}
&#10;#vaayhctool .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 15px;
  padding-right: 15px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}
&#10;#vaayhctool .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 15px;
  padding-right: 15px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}
&#10;#vaayhctool .gt_heading {
  background-color: #FFFFFF;
  text-align: left;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}
&#10;#vaayhctool .gt_bottom_border {
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
&#10;#vaayhctool .gt_col_headings {
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #000000;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}
&#10;#vaayhctool .gt_col_heading {
  color: #333333;
  background-color: #E5E5E5;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 15px;
  padding-right: 15px;
  overflow-x: hidden;
}
&#10;#vaayhctool .gt_column_spanner_outer {
  color: #333333;
  background-color: #E5E5E5;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}
&#10;#vaayhctool .gt_column_spanner_outer:first-child {
  padding-left: 0;
}
&#10;#vaayhctool .gt_column_spanner_outer:last-child {
  padding-right: 0;
}
&#10;#vaayhctool .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #000000;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}
&#10;#vaayhctool .gt_spanner_row {
  border-bottom-style: hidden;
}
&#10;#vaayhctool .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #000000;
  border-bottom-style: solid;
  border-bottom-width: 1px;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}
&#10;#vaayhctool .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #000000;
  border-bottom-style: solid;
  border-bottom-width: 1px;
  border-bottom-color: #FFFFFF;
  vertical-align: middle;
}
&#10;#vaayhctool .gt_from_md > :first-child {
  margin-top: 0;
}
&#10;#vaayhctool .gt_from_md > :last-child {
  margin-bottom: 0;
}
&#10;#vaayhctool .gt_row {
  padding-top: 3px;
  padding-bottom: 3px;
  padding-left: 15px;
  padding-right: 15px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}
&#10;#vaayhctool .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 0px;
  border-right-color: #FFFFFF;
  padding-left: 15px;
  padding-right: 15px;
}
&#10;#vaayhctool .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 15px;
  padding-right: 15px;
  vertical-align: top;
}
&#10;#vaayhctool .gt_row_group_first td {
  border-top-width: 2px;
}
&#10;#vaayhctool .gt_row_group_first th {
  border-top-width: 2px;
}
&#10;#vaayhctool .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
}
&#10;#vaayhctool .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}
&#10;#vaayhctool .gt_first_summary_row.thick {
  border-top-width: 2px;
}
&#10;#vaayhctool .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
&#10;#vaayhctool .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
}
&#10;#vaayhctool .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}
&#10;#vaayhctool .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}
&#10;#vaayhctool .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}
&#10;#vaayhctool .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
&#10;#vaayhctool .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}
&#10;#vaayhctool .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 15px;
  padding-right: 15px;
}
&#10;#vaayhctool .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}
&#10;#vaayhctool .gt_sourcenote {
  font-size: 12px;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 15px;
  padding-right: 15px;
}
&#10;#vaayhctool .gt_left {
  text-align: left;
}
&#10;#vaayhctool .gt_center {
  text-align: center;
}
&#10;#vaayhctool .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}
&#10;#vaayhctool .gt_font_normal {
  font-weight: normal;
}
&#10;#vaayhctool .gt_font_bold {
  font-weight: bold;
}
&#10;#vaayhctool .gt_font_italic {
  font-style: italic;
}
&#10;#vaayhctool .gt_super {
  font-size: 65%;
}
&#10;#vaayhctool .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}
&#10;#vaayhctool .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}
&#10;#vaayhctool .gt_indent_1 {
  text-indent: 5px;
}
&#10;#vaayhctool .gt_indent_2 {
  text-indent: 10px;
}
&#10;#vaayhctool .gt_indent_3 {
  text-indent: 15px;
}
&#10;#vaayhctool .gt_indent_4 {
  text-indent: 20px;
}
&#10;#vaayhctool .gt_indent_5 {
  text-indent: 25px;
}
&#10;#vaayhctool .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}
&#10;#vaayhctool div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
&#10;#vaayhctool tbody tr:last-child {
  border-bottom: 2px solid #ffffff00;
}
</style>

| Store City | Total Revenue (\$) | Total Number Of Orders |
|------------|--------------------|------------------------|
| city A     | \$15,864           | 358                    |
| city B     | \$15,827           | 337                    |
| city C     | \$15,854           | 354                    |

</div>

***City A has highest total revenue and number of orders (\$15K , 358) ,
followed by City C (\$15K , 354) then City B (\$15K , 354)***

***Given City A has total revenue and number of orders , indicating high
demand , we recommend increasing marketing spend / effort in City A to
acquire new customers build of existing momentum***

### Direct new customers to store “wehqk” (best operational excellence) , to acquire new customers and increase customer retention

<div id="cwzaieurvs" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>@import url("https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Cairo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
#cwzaieurvs table {
  font-family: Cairo, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
&#10;#cwzaieurvs thead, #cwzaieurvs tbody, #cwzaieurvs tfoot, #cwzaieurvs tr, #cwzaieurvs td, #cwzaieurvs th {
  border-style: none;
}
&#10;#cwzaieurvs p {
  margin: 0;
  padding: 0;
}
&#10;#cwzaieurvs .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: 400;
  font-style: normal;
  background-color: #FFFFFF;
  width: 450px;
  border-top-style: none;
  border-top-width: 3px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}
&#10;#cwzaieurvs .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 15px;
  padding-right: 15px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}
&#10;#cwzaieurvs .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 15px;
  padding-right: 15px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}
&#10;#cwzaieurvs .gt_heading {
  background-color: #FFFFFF;
  text-align: left;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_bottom_border {
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_col_headings {
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #000000;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_col_heading {
  color: #333333;
  background-color: #E5E5E5;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 15px;
  padding-right: 15px;
  overflow-x: hidden;
}
&#10;#cwzaieurvs .gt_column_spanner_outer {
  color: #333333;
  background-color: #E5E5E5;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}
&#10;#cwzaieurvs .gt_column_spanner_outer:first-child {
  padding-left: 0;
}
&#10;#cwzaieurvs .gt_column_spanner_outer:last-child {
  padding-right: 0;
}
&#10;#cwzaieurvs .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #000000;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}
&#10;#cwzaieurvs .gt_spanner_row {
  border-bottom-style: hidden;
}
&#10;#cwzaieurvs .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #000000;
  border-bottom-style: solid;
  border-bottom-width: 1px;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}
&#10;#cwzaieurvs .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #000000;
  border-bottom-style: solid;
  border-bottom-width: 1px;
  border-bottom-color: #FFFFFF;
  vertical-align: middle;
}
&#10;#cwzaieurvs .gt_from_md > :first-child {
  margin-top: 0;
}
&#10;#cwzaieurvs .gt_from_md > :last-child {
  margin-bottom: 0;
}
&#10;#cwzaieurvs .gt_row {
  padding-top: 3px;
  padding-bottom: 3px;
  padding-left: 15px;
  padding-right: 15px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}
&#10;#cwzaieurvs .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 0px;
  border-right-color: #FFFFFF;
  padding-left: 15px;
  padding-right: 15px;
}
&#10;#cwzaieurvs .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 15px;
  padding-right: 15px;
  vertical-align: top;
}
&#10;#cwzaieurvs .gt_row_group_first td {
  border-top-width: 2px;
}
&#10;#cwzaieurvs .gt_row_group_first th {
  border-top-width: 2px;
}
&#10;#cwzaieurvs .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
}
&#10;#cwzaieurvs .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_first_summary_row.thick {
  border-top-width: 2px;
}
&#10;#cwzaieurvs .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
}
&#10;#cwzaieurvs .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}
&#10;#cwzaieurvs .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 15px;
  padding-right: 15px;
}
&#10;#cwzaieurvs .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_sourcenote {
  font-size: 12px;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 15px;
  padding-right: 15px;
}
&#10;#cwzaieurvs .gt_left {
  text-align: left;
}
&#10;#cwzaieurvs .gt_center {
  text-align: center;
}
&#10;#cwzaieurvs .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}
&#10;#cwzaieurvs .gt_font_normal {
  font-weight: normal;
}
&#10;#cwzaieurvs .gt_font_bold {
  font-weight: bold;
}
&#10;#cwzaieurvs .gt_font_italic {
  font-style: italic;
}
&#10;#cwzaieurvs .gt_super {
  font-size: 65%;
}
&#10;#cwzaieurvs .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}
&#10;#cwzaieurvs .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}
&#10;#cwzaieurvs .gt_indent_1 {
  text-indent: 5px;
}
&#10;#cwzaieurvs .gt_indent_2 {
  text-indent: 10px;
}
&#10;#cwzaieurvs .gt_indent_3 {
  text-indent: 15px;
}
&#10;#cwzaieurvs .gt_indent_4 {
  text-indent: 20px;
}
&#10;#cwzaieurvs .gt_indent_5 {
  text-indent: 25px;
}
&#10;#cwzaieurvs .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}
&#10;#cwzaieurvs div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
&#10;#cwzaieurvs tbody tr:last-child {
  border-bottom: 2px solid #ffffff00;
}
</style>

| Store ID | Total Refund (\$) | Average Rating | Average Order Prep Time (h:m:s) |
|----------|-------------------|----------------|---------------------------------|
| acjde    | \$401             | 3.16           | 00:09:50                        |
| bjdwe    | \$398             | 3.64           | 00:09:59                        |
| wehqk    | \$394             | 3.74           | 00:09:55                        |

</div>

***Store “wehqk” has the lowest refund total , best average rating and
second best average order preparation time (\$394 ,3.74 ,9m 55s)***

***Given that Store “wehqk” has the best operational excellence , we
recommend directing new customers gained via marketing campaigns to this
store as it would leave good impressions on new users , leading to
repeat orders and customer retention***

### Take actions (better staff training e.t.c) in Store “wehqk” (worst operational excellence) to increase customer retention

<div id="cwzaieurvs" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>@import url("https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Cairo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
#cwzaieurvs table {
  font-family: Cairo, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
&#10;#cwzaieurvs thead, #cwzaieurvs tbody, #cwzaieurvs tfoot, #cwzaieurvs tr, #cwzaieurvs td, #cwzaieurvs th {
  border-style: none;
}
&#10;#cwzaieurvs p {
  margin: 0;
  padding: 0;
}
&#10;#cwzaieurvs .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: 400;
  font-style: normal;
  background-color: #FFFFFF;
  width: 450px;
  border-top-style: none;
  border-top-width: 3px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}
&#10;#cwzaieurvs .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 15px;
  padding-right: 15px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}
&#10;#cwzaieurvs .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 15px;
  padding-right: 15px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}
&#10;#cwzaieurvs .gt_heading {
  background-color: #FFFFFF;
  text-align: left;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_bottom_border {
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_col_headings {
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #000000;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_col_heading {
  color: #333333;
  background-color: #E5E5E5;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 15px;
  padding-right: 15px;
  overflow-x: hidden;
}
&#10;#cwzaieurvs .gt_column_spanner_outer {
  color: #333333;
  background-color: #E5E5E5;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}
&#10;#cwzaieurvs .gt_column_spanner_outer:first-child {
  padding-left: 0;
}
&#10;#cwzaieurvs .gt_column_spanner_outer:last-child {
  padding-right: 0;
}
&#10;#cwzaieurvs .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #000000;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}
&#10;#cwzaieurvs .gt_spanner_row {
  border-bottom-style: hidden;
}
&#10;#cwzaieurvs .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #000000;
  border-bottom-style: solid;
  border-bottom-width: 1px;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}
&#10;#cwzaieurvs .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #000000;
  border-bottom-style: solid;
  border-bottom-width: 1px;
  border-bottom-color: #FFFFFF;
  vertical-align: middle;
}
&#10;#cwzaieurvs .gt_from_md > :first-child {
  margin-top: 0;
}
&#10;#cwzaieurvs .gt_from_md > :last-child {
  margin-bottom: 0;
}
&#10;#cwzaieurvs .gt_row {
  padding-top: 3px;
  padding-bottom: 3px;
  padding-left: 15px;
  padding-right: 15px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}
&#10;#cwzaieurvs .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 0px;
  border-right-color: #FFFFFF;
  padding-left: 15px;
  padding-right: 15px;
}
&#10;#cwzaieurvs .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 15px;
  padding-right: 15px;
  vertical-align: top;
}
&#10;#cwzaieurvs .gt_row_group_first td {
  border-top-width: 2px;
}
&#10;#cwzaieurvs .gt_row_group_first th {
  border-top-width: 2px;
}
&#10;#cwzaieurvs .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
}
&#10;#cwzaieurvs .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_first_summary_row.thick {
  border-top-width: 2px;
}
&#10;#cwzaieurvs .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
}
&#10;#cwzaieurvs .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 15px;
  padding-right: 15px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}
&#10;#cwzaieurvs .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 15px;
  padding-right: 15px;
}
&#10;#cwzaieurvs .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}
&#10;#cwzaieurvs .gt_sourcenote {
  font-size: 12px;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 15px;
  padding-right: 15px;
}
&#10;#cwzaieurvs .gt_left {
  text-align: left;
}
&#10;#cwzaieurvs .gt_center {
  text-align: center;
}
&#10;#cwzaieurvs .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}
&#10;#cwzaieurvs .gt_font_normal {
  font-weight: normal;
}
&#10;#cwzaieurvs .gt_font_bold {
  font-weight: bold;
}
&#10;#cwzaieurvs .gt_font_italic {
  font-style: italic;
}
&#10;#cwzaieurvs .gt_super {
  font-size: 65%;
}
&#10;#cwzaieurvs .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}
&#10;#cwzaieurvs .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}
&#10;#cwzaieurvs .gt_indent_1 {
  text-indent: 5px;
}
&#10;#cwzaieurvs .gt_indent_2 {
  text-indent: 10px;
}
&#10;#cwzaieurvs .gt_indent_3 {
  text-indent: 15px;
}
&#10;#cwzaieurvs .gt_indent_4 {
  text-indent: 20px;
}
&#10;#cwzaieurvs .gt_indent_5 {
  text-indent: 25px;
}
&#10;#cwzaieurvs .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}
&#10;#cwzaieurvs div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
&#10;#cwzaieurvs tbody tr:last-child {
  border-bottom: 2px solid #ffffff00;
}
</style>

| Store ID | Total Refund (\$) | Average Rating | Average Order Prep Time (h:m:s) |
|----------|-------------------|----------------|---------------------------------|
| acjde    | \$401             | 3.16           | 00:09:50                        |
| bjdwe    | \$398             | 3.64           | 00:09:59                        |
| wehqk    | \$394             | 3.74           | 00:09:55                        |

</div>

***Store “acjde” has the highest refund total , lowest average rating
and best average order preparation time (\$401, 3.16, 9m 50s)***

***Given that Store “wehqk” has the worst operational excellence , we
recommend looking into root causes , taking actions to improve
operational excellence (better staff training , running customer surveys
, e.t.c) , to improve customer retention by improving service
delivery***

## Opportunity 2 : Increasing number of times customers order per week

### Send email / push notifications around 2AM-6AM and 8PM-9PM (popular ordering time) to increase order frequency

![](eda_files/figure-commonmark/unnamed-chunk-8-1.png)

***Daily place order times has two sales peaks , one around 2AM-6AM and
the other at around 8PM-9PM .***

***Given that daily sales peak around 2AM-6AM and 8PM-9PM , which
correspond to popular ordering times , we recommend sending email / push
notification reminders to our customers around these time , to increase
order frequency***

## Opportunity 3 : Increasing number of drinks per order

### Offer exclusive promotion / offers to customers with average order size below the average , to increase number of drinks per order

![](eda_files/figure-commonmark/unnamed-chunk-9-1.png)

<div id="zgpzmplvls" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>@import url("https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Chivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Cairo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
#zgpzmplvls table {
  font-family: Cairo, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
&#10;#zgpzmplvls thead, #zgpzmplvls tbody, #zgpzmplvls tfoot, #zgpzmplvls tr, #zgpzmplvls td, #zgpzmplvls th {
  border-style: none;
}
&#10;#zgpzmplvls p {
  margin: 0;
  padding: 0;
}
&#10;#zgpzmplvls .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: 400;
  font-style: normal;
  background-color: #FFFFFF;
  width: 400px;
  border-top-style: none;
  border-top-width: 3px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}
&#10;#zgpzmplvls .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}
&#10;#zgpzmplvls .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}
&#10;#zgpzmplvls .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}
&#10;#zgpzmplvls .gt_heading {
  background-color: #FFFFFF;
  text-align: left;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}
&#10;#zgpzmplvls .gt_bottom_border {
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
&#10;#zgpzmplvls .gt_col_headings {
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #000000;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}
&#10;#zgpzmplvls .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}
&#10;#zgpzmplvls .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}
&#10;#zgpzmplvls .gt_column_spanner_outer:first-child {
  padding-left: 0;
}
&#10;#zgpzmplvls .gt_column_spanner_outer:last-child {
  padding-right: 0;
}
&#10;#zgpzmplvls .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #000000;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}
&#10;#zgpzmplvls .gt_spanner_row {
  border-bottom-style: hidden;
}
&#10;#zgpzmplvls .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #000000;
  border-bottom-style: solid;
  border-bottom-width: 1px;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}
&#10;#zgpzmplvls .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #000000;
  border-bottom-style: solid;
  border-bottom-width: 1px;
  border-bottom-color: #FFFFFF;
  vertical-align: middle;
}
&#10;#zgpzmplvls .gt_from_md > :first-child {
  margin-top: 0;
}
&#10;#zgpzmplvls .gt_from_md > :last-child {
  margin-bottom: 0;
}
&#10;#zgpzmplvls .gt_row {
  padding-top: 3px;
  padding-bottom: 3px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}
&#10;#zgpzmplvls .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 0px;
  border-right-color: #FFFFFF;
  padding-left: 5px;
  padding-right: 5px;
}
&#10;#zgpzmplvls .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}
&#10;#zgpzmplvls .gt_row_group_first td {
  border-top-width: 2px;
}
&#10;#zgpzmplvls .gt_row_group_first th {
  border-top-width: 2px;
}
&#10;#zgpzmplvls .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}
&#10;#zgpzmplvls .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}
&#10;#zgpzmplvls .gt_first_summary_row.thick {
  border-top-width: 2px;
}
&#10;#zgpzmplvls .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
&#10;#zgpzmplvls .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}
&#10;#zgpzmplvls .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}
&#10;#zgpzmplvls .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}
&#10;#zgpzmplvls .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}
&#10;#zgpzmplvls .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
&#10;#zgpzmplvls .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}
&#10;#zgpzmplvls .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}
&#10;#zgpzmplvls .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}
&#10;#zgpzmplvls .gt_sourcenote {
  font-size: 12px;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}
&#10;#zgpzmplvls .gt_left {
  text-align: left;
}
&#10;#zgpzmplvls .gt_center {
  text-align: center;
}
&#10;#zgpzmplvls .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}
&#10;#zgpzmplvls .gt_font_normal {
  font-weight: normal;
}
&#10;#zgpzmplvls .gt_font_bold {
  font-weight: bold;
}
&#10;#zgpzmplvls .gt_font_italic {
  font-style: italic;
}
&#10;#zgpzmplvls .gt_super {
  font-size: 65%;
}
&#10;#zgpzmplvls .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}
&#10;#zgpzmplvls .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}
&#10;#zgpzmplvls .gt_indent_1 {
  text-indent: 5px;
}
&#10;#zgpzmplvls .gt_indent_2 {
  text-indent: 10px;
}
&#10;#zgpzmplvls .gt_indent_3 {
  text-indent: 15px;
}
&#10;#zgpzmplvls .gt_indent_4 {
  text-indent: 20px;
}
&#10;#zgpzmplvls .gt_indent_5 {
  text-indent: 25px;
}
&#10;#zgpzmplvls .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}
&#10;#zgpzmplvls div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
&#10;#zgpzmplvls tbody tr:last-child {
  border-bottom: 2px solid #ffffff00;
}
</style>

| n   | Percent (%) |
|-----|-------------|
| 230 | 48%         |

</div>

***Almost half of our customers (48%) have average order sizes below the
average of 5 drinks per orders***

***Given that almost half of our customers order less than 5 drinks per
order , we recommend offering special promotions (e.g get 10% off when
you order 5 drinks) , to increase number of drinks per order .***
